// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGmpb15c3ooytrEOjp4tDly62u1XlphZI',
    appId: '1:403790800210:web:be9182c4d2c190423f468b',
    messagingSenderId: '403790800210',
    projectId: 'hostelbuddy-1226f',
    authDomain: 'hostelbuddy-1226f.firebaseapp.com',
    storageBucket: 'hostelbuddy-1226f.appspot.com',
    measurementId: 'G-3C32D146EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEmSnclG8fvIEn5jxKNTKNGZldNHoieJA',
    appId: '1:403790800210:android:ad5f0bdb9228ec743f468b',
    messagingSenderId: '403790800210',
    projectId: 'hostelbuddy-1226f',
    storageBucket: 'hostelbuddy-1226f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5P-WhCMaN13RBkNqe5pPsrL_u0G_SH2I',
    appId: '1:403790800210:ios:4978515211ef2d683f468b',
    messagingSenderId: '403790800210',
    projectId: 'hostelbuddy-1226f',
    storageBucket: 'hostelbuddy-1226f.appspot.com',
    iosBundleId: 'com.example.hostelBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5P-WhCMaN13RBkNqe5pPsrL_u0G_SH2I',
    appId: '1:403790800210:ios:4978515211ef2d683f468b',
    messagingSenderId: '403790800210',
    projectId: 'hostelbuddy-1226f',
    storageBucket: 'hostelbuddy-1226f.appspot.com',
    iosBundleId: 'com.example.hostelBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGmpb15c3ooytrEOjp4tDly62u1XlphZI',
    appId: '1:403790800210:web:2c2e0c0abf9ad62f3f468b',
    messagingSenderId: '403790800210',
    projectId: 'hostelbuddy-1226f',
    authDomain: 'hostelbuddy-1226f.firebaseapp.com',
   storageBucket: 'hostelbuddy-1226f.appspot.com',
    measurementId: 'G-ZWDV5GRGZV',
  );
}
